# Use official Node.js image as base
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /next-with-docker

# Copy package.json and package-lock.json to container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Next.js app only for production build
# RUN npm run build

# Expose port 3000
EXPOSE 3000

# Command to run the Next.js app
CMD ["npm", "run","dev"]
