version: "3"
services:
  next-with-docker:
    container_name: next-with-docker-container
    image: next-with-docker-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/next-with-docker
